# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

table_1d_fast <- function(input, n) {
    .Call('_SpaTopic_table_1d_fast', PACKAGE = 'SpaTopic', input, n)
}

table_2d_fast <- function(lhs, rhs, n_lhs, n_rhs) {
    .Call('_SpaTopic_table_2d_fast', PACKAGE = 'SpaTopic', lhs, rhs, n_lhs, n_rhs)
}

compute_loglike <- function(m_theta, m_beta, docs, neighbors, Kernel, M, n_words, K, beta = .05, alpha = .01, sigma = 50) {
    .Call('_SpaTopic_compute_loglike', PACKAGE = 'SpaTopic', m_theta, m_beta, docs, neighbors, Kernel, M, n_words, K, beta, alpha, sigma)
}

gibbs_lda_c <- function(docs, Ndk, Nwk, Nk, Z, D, doc_list, word_list, K, niter = 20L, beta = .05, alpha = .01) {
    .Call('_SpaTopic_gibbs_lda_c', PACKAGE = 'SpaTopic', docs, Ndk, Nwk, Nk, Z, D, doc_list, word_list, K, niter, beta, alpha)
}

gibbs_sampler_c <- function(docs, Ndk, Nwk, Nk, Nd, Z, D, dists, neighbors, doc_list, word_list, K, beta = .05, alpha = .01, sigma = 50, thin = 20L, burnin = 1000L, niter = 200L, trace = FALSE, display_progress = TRUE) {
    .Call('_SpaTopic_gibbs_sampler_c', PACKAGE = 'SpaTopic', docs, Ndk, Nwk, Nk, Nd, Z, D, dists, neighbors, doc_list, word_list, K, beta, alpha, sigma, thin, burnin, niter, trace, display_progress)
}

